version: '2'

services:
    remark:
        build:
          context: .
          args:
            - REMARK_URL=${REMARK_URL}
        image: umputun/remark:master
        container_name: "remark"
        hostname: "remark"
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        # uncomment to expose directly (no proxy)
        ports:
          - "80:8080"

        environment:
            # - REMARK_URL=https://demo.remark42.com
            - REMARK_URL
            - BOLTDB_PATH=/srv/var/db
            - BACKUP_PATH=/srv/var/backup
            - SESSION_STORE=/srv/var/session
            # - DEV_PASSWD=password # development mode, be careful!
            - DEBUG=true
            - REMARK_GOOGLE_CID
            - REMARK_GOOGLE_CSEC
            - REMARK_GITHUB_CID
            - REMARK_GITHUB_CSEC
            - REMARK_FACEBOOK_CID
            - REMARK_FACEBOOK_CSEC
            - REMARK_DISQUS_CID
            - REMARK_DISQUS_CSEC
        volumes:
            - ./var:/srv/var
            #- ./web:/srv/web # uncomment to map web directory directly. It will propagate local changes to container without redeploy

        user: ${USER} # if local UID != 1001 (default) set `USER` in your env, i.e. export USER=`id -u $USER`
        command: /srv/start.sh
