version: '2'

services:
    remark:
        build: .
        image: umputun/remark:master
        container_name: "remark"
        hostname: "remark"
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        ports:
            - "8080:8080"

        environment:
            - REMARK_URL=https://demo.remark42.com
            - BOLTDB_PATH=/srv/var/db
            - BACKUP_PATH=/srv/var/backup
            - SESSION_STORE=/srv/var/session
            - DEV=true # development mode flag. It turns authentication off, be careful!
            - DEBUG=true

        volumes:
            - ./var:/srv/var
            - ./web:/srv/web # maps web directory directly to propagate local changes to container without redeploy

        command: /srv/remark server
