[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.0.0"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/logutils"

[[constraint]]
  branch = "master"
  name = "github.com/microcosm-cc/bluemonday"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[constraint]]
  name = "gopkg.in/russross/blackfriday.v2"
  version = "2.0.0"

[prune]
  go-tests = true
  unused-packages = true
