name: frontend

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/ci-frontend.yml"
      - "frontend/apps/remark42/**"
      - "!**.md"
  pull_request:
    paths:
      - ".github/workflows/ci-frontend.yml"
      - "frontend/apps/remark42/**"
      - "!**.md"

jobs:
  translations-check:
    name: Translations check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i
        working-directory: ./frontend

      - name: Translations check
        run: pnpm translation-check
        working-directory: ./frontend/apps/remark42

  type-check:
    name: Type check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i
        working-directory: ./frontend

      - name: Run type check
        run: pnpm type-check
        working-directory: ./frontend/apps/remark42

  lint:
    name: Eslint & Stylelint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i
        working-directory: ./frontend

      - name: Run linters
        run: pnpm lint
        working-directory: ./frontend/apps/remark42

  size-limit:
    name: Size limit
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Check bundle size
        uses: andresz1/size-limit-action@94bc357df29c36c8f8d50ea497c3e225c3c95d1d
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: ./frontend/apps/remark42
          package_manager: pnpm

  test:
    name: Tests & Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i
        working-directory: ./frontend

      - name: Test & Coverage
        run: pnpm coverage
        working-directory: ./frontend/apps/remark42

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          working-directory: ./frontend/apps/remark42
          codecov_yml_path: ./frontend/apps/remark42/codecov.yml
